### ISSUE TITLE
突然无法使用composer安装该sdk

### ISSUE THREAD

**Issue by twelife** [TencentCloud/tencentcloud-sdk-php#101]
使用 `composer` 安装就一直卡进度，如下图所示，上面一个是本地的，下面一个是服务器的。

`composer` 版本：`2.0.14`

`php` 版本：`7.4`

![image](https://user-images.githubusercontent.com/8390752/148502883-9428ad20-c533-4e3b-830c-962e40698118.png)

**Comment by zqfan** [comment]
这种情况一般是本地环境和服务器之间的网络通信问题导致的。
我本地测试正常：
![image](https://user-images.githubusercontent.com/2180987/148639064-7548cb6b-b753-4c64-ba4b-7abdb41a8883.png)
