### ISSUE TITLE
DescribeDeviceDataRequest中命名错误，导致的返回失败问题

### ISSUE THREAD

**Issue by wo134150** [TencentCloud/tencentcloud-sdk-php#107]
use TencentCloud\Iotexplorer\V20190423\Models\DescribeDeviceDataRequest;
文件中
/**
     * @var string 产品ID
     */
    public $ProductID;     定了一个变量 ProductID， 实际上使用去请求腾讯云的时候会返回  ProductId不能为空的错误提示

这边建议修改下字段名为 ----ProductId，这样能更好兼容腾讯云iot调用

**Comment by zqfan** [comment]
变量名大小写是正确的啊，ProductId
https://github.com/TencentCloud/tencentcloud-sdk-php/blob/master/src/TencentCloud/Iotexplorer/V20190423/Models/DescribeDeviceDataRequest.php#L35
![image](https://user-images.githubusercontent.com/2180987/176580090-929242f2-b25f-4007-80ac-8bc441e1d0e6.png)

**Comment by wo134150** [comment]
这就很奇怪了，我用阿里云拉下来的本地和服务器环境都是大写的ProductID，刚刚还去确认了下

**Comment by zqfan** [comment]
这个文件上次更新还是两年前，
