### ISSUE TITLE
为什么要把 vendor 目录提交上来？

### ISSUE THREAD

**Issue by wudi** [TencentCloud/tencentcloud-sdk-php#11]
保留 composer.json 即可，vendor 没必要。

**Comment by tourze** [comment]
我觉得这个issue不应该关闭的，的确vendor提交上来不合理。

**Comment by wudi** [comment]
vendor 提交上来，居然还没有 composer 类库。

**Comment by zqfan** [comment]
因为有些国内开发者不使用composer或其他包管理工具管理依赖，而是直接使用源码的方式，为此需要把依赖的文件放进代码仓库中。vendor目录虽然被提交了，但是不会导出，并不会影响到composer的用户。

**Comment by tourze** [comment]
特地搞个sdk就不用做那类兼容了吧。。。不会影响到composer的用户，但是开发还是有点困恼的

**Comment by zqfan** [comment]
开发有困恼具体指什么？使用composer的时候此vendor目录不会下载的。
不论如何，那些用户真实存在，我们又没有精力去教他们什么才是生产力较高的方式

**Comment by tourze** [comment]
我刚确认了一下，的确 `composer require tencentcloud/tencentcloud-sdk-php` 没问题了
![image](https://user-images.githubusercontent.com/13899502/58373317-dba22200-7f5e-11e9-91ea-273cf3b22e60.png)
