### ISSUE TITLE
SSL证书，“忽略证书”接口缺失

### ISSUE THREAD

**Issue by qcgzxw** [TencentCloud/tencentcloud-sdk-php#111]
想需要通过API关闭未使用SSL证书的通知，不然就算部署了自动更新证书，旧的SSL还是会发过期提醒。

该功能可以在控制台实现
![image](https://user-images.githubusercontent.com/24518597/190043405-9bf2c26e-d63b-4ada-acdd-1634be5c4092.png)

控制台看到的请求是
```
cmd: ModifyCertificatesExpiringNotificationSwitch
action: delegate
serviceType: ssl
```

希望能补全

**Comment by zqfan** [comment]
此接口已开放：https://github.com/TencentCloud/tencentcloud-sdk-php/blob/master/src/TencentCloud/Ssl/V20191205/Models/ModifyCertificatesExpiringNotificationSwitchRequest.php
