### ISSUE TITLE
这个 SDK 到底在搞什么，100多M，WTF

### ISSUE THREAD

**Issue by holla-wangqiang** [TencentCloud/tencentcloud-sdk-php#113]
离大谱，一个 SDK 竟然有 107M，一个项目 vendor 这个 SDK 占了三分之二，AWS SDK 包 16M，Aliyun SDK 包 19M。

上点心吧腾讯云的同志。

**Comment by holla-wangqiang** [comment]
还有就是腾讯云维护的 composer 源，那叫个啥？包版本老旧、缺失，建议还是别写在 README 了，耽误别人时间。

**Comment by zqfan** [comment]
aws和aliyun sdk中都没有对接口和参数的注释，所以包体积看起来会小很多。如果你仅使用到特定的产品，可以只下载该产品对应的分包，不用下载所有产品的大包，分包的体积只有几百K到几M左右。
腾讯云composer源更新不及时的问题，可以到腾讯云官网控制台工单系统提单反馈。

**Comment by holla-wangqiang** [comment]
> 腾讯云composer源更新不及时的问题，可以到腾讯云官网控制台工单系统提单反馈。

踢皮球？要不我给你提个 PR 把 README 的 composer 源改为 aliyun？

**Comment by zqfan** [comment]
> > 腾讯云composer源更新不及时的问题，可以到腾讯云官网控制台工单系统提单反馈。
> 
> 踢皮球？要不我给你提个 PR 把 README 的 composer 源改为 aliyun？

工单有催单的机制啊，而且是和你直接沟通的，从解决问题的效率来看是更高的
