### ISSUE TITLE
The request is missing a required parameter `BeginTime`.

### ISSUE THREAD

**Issue by salinmu** [TencentCloud/tencentcloud-sdk-php#114]
一年前还用得好好的，现在怎么报这个错误了

伪代码：
            (new \TencentCloud\Sms\V20210111\SmsClient(new \TencentCloud\Common\Credential($this->secretId, $this->secretKey), "ap-guangzhou"))->PullSmsSendStatusByPhoneNumber(new \TencentCloud\Sms\V20210111\Models\PullSmsReplyStatusByPhoneNumberRequest());
抛出异常文件：/vendor/tencentcloud/tencentcloud-sdk-php/src/TencentCloud/Common/AbstractClient.php(175)
抛出异常：\TencentCloud\Common\Exception\TencentCloudSDKException
异常信息：The request is missing a required parameter BeginTime

**Comment by zqfan** [comment]
请问有完整的堆栈吗？

**Comment by salinmu** [comment]
已解决
