### ISSUE TITLE
Composer安装tencentcloud-sdk-php报超时错误

### ISSUE THREAD

**Issue by jefferyjob** [TencentCloud/tencentcloud-sdk-php#116]
### 事件背景
- php版本：7.4
- composer版本：2.5

### 报错信息

```
 118/119 [===========================>]  99%    Install of tencentcloud/tencentcloud-sdk-php failed
The following exception is caused by a process timeout
Check https://getcomposer.org/doc/06-config.md#process-timeout for details

In Process.php line 1204:
                                                                                                                                                      
  The process "'/usr/bin/unzip' -qq '/www/admin/admin_api/vendor/composer/tmp-10c5f410f6f028455c97508e349bec93' -d '/www/admin/admin_api/vendor/comp  
  oser/0431e91f'" exceeded the timeout of 300 seconds.   
```

我尝试使用了阿里云的composer镜像，使用了腾讯云的composer镜像，还使用了vpn，都是这个问题。有人遇到过这个问题吗？

**Comment by jefferyjob** [comment]
composr.json 具体定义的版本如下

"tencentcloud/tencentcloud-sdk-php": "3.0.506",

**Comment by zqfan** [comment]
1、安装下对应产品的分包看能否解决，例如composer require tencentcloud/cvm，分包体积小很多，如果是网络质量不太好，可以试试
2、按照官方指引，禁掉默认的300s超时：
![image](https://github.com/TencentCloud/tencentcloud-sdk-php/assets/2180987/999a3496-b853-4bdc-addc-f7a0186708af)

**Comment by HankChenCH** [comment]
同样问题，分包下载依然会下载整个sdk，然后解压超久

**Comment by zqfan** [comment]
分包下载实测不会下载整个sdk啊，解压后目录大小只有2MB
![image](https://github.com/TencentCloud/tencentcloud-sdk-php/assets/2180987/3bdc6ee5-2e3a-4fad-a319-671ee58a89d4)

**Comment by HankChenCH** [comment]
> tencentcloud

不好意思，可能composer文件没删除干净依赖，导致下载的时候会整包下载，现在重试可以了
