### ISSUE TITLE
云点播 获取媒体详细信息 有详细的使用文档吗？不知道如何调用

### ISSUE THREAD

**Issue by xlkit456852** [TencentCloud/tencentcloud-sdk-php#13]
如题，谢谢~

**Comment by zqfan** [comment]
sdk对接口和字段的描述和官网文档是一致的，https://cloud.tencent.com/document/api/266/31763  ，但是并没有像官网文档那样提供示例和错误码，你也可以试试API Explorer：https://console.cloud.tencent.com/api/explorer?Product=vod&Version=2018-07-17&Action=DescribeMediaInfos
