### ISSUE TITLE
输入音频分片长度应该为偶数

### ISSUE THREAD

**Issue by swkcc** [TencentCloud/tencentcloud-sdk-php#18]
一次性评测报错：输入音频分片长度应该为偶数

**Comment by zqfan** [comment]
能否再具体点？你说的这些我连官网搜文档都搜不出来，不知道具体说的是哪个接口

**Comment by swkcc** [comment]
soe模块 调用TransmitOralProcessWithInitRequest模型时报这个错。我们测试了很多自己输入的语言，只有少数能识别，大多数都返回：输入音频分片长度应该为偶数 错误

**Comment by zqfan** [comment]
https://cloud.tencent.com/document/product/884/32605 
这个？
![image](https://user-images.githubusercontent.com/2180987/54863169-6197c600-4d80-11e9-8a90-3c0ad6856284.png)

**Comment by swkcc** [comment]
'SeqId'=>1,
			'IsEnd'=>1,
			'VoiceFileType'=>2,
			'VoiceEncodeType'=>1,
			'UserVoiceData'=>$void,
			'SessionId'=>$id,
			'RefText' => $void_text,
			'WorkMode' => 1,
			'EvalMode' => 1,
			'ScoreCoeff' => 1.5,
			'StorageMode' => 0,
			'ServerType' => 0,
			'TextMode' => 0  这些是我的传的参数不是流式的，除非WorkMode这个字段没有判断

**Comment by swkcc** [comment]
我用官方文档的流数据UserVoiceData=VWtsR1JxeUpBd0JYUVZaRlptMTBJQkFBQUFBQkFBRUFnRDRBQUFCOUFBQUNBQkFBVEVsVFZCb0FBQUJKVGtaUFNWTkdWQTRBQUFCTVlYWm1OVFl1TVRrdU1UQXdBR1JoZEdGbWlRTUF5 试了下也是提示：输入音频分片长度应该为偶数。希望作者提供一个完善的解决方案

**Comment by zqfan** [comment]
官方文档只是举例子，介绍下用法，有些人看不懂base64是啥，因此用一段base64的数据，以免他们直接用二进制数据怼。文档中对UserVoiceData要求大于4KB，你觉得这个例子中的长度有4KB吗？
而且这和作者有什么关系，这是这个服务的API接口做的规定。作为服务的使用者，按照接口的要求进行语音数据切片传输时，需要按偶数切也是个合理的决定啊

**Comment by swkcc** [comment]
现在问题不是说切片不切片， 我想问下WorkMode为1时，是一次性评测，不需要切片。还是需要？如果方便留个电话，我直接咨询您

**Comment by zqfan** [comment]
workmode=1时不需要切片，一次传输完毕，但是应该支持不了太大的数据，你可以711269805
