### ISSUE TITLE
接口更新之后 lb负载均衡 ReplaceCert 老版v2无法调用，新版没有对应的api

### ISSUE THREAD

**Issue by munggruel** [TencentCloud/tencentcloud-sdk-php#2]
https://lb.api.qcloud.com/v2/index.php?SignatureMethod=HmacSHA256&oldCertId=Ku8h1lfR&newCertContent=XXXX&newCertKey=XXXX&newCertName=20180601&Action=ReplaceCert&Region=sh&SecretId=XXXX&Nonce=41202&Timestamp=1527829418&RequestClient=SDK_PHP_2.0.6&Signature=XXXX

在php端 提示错误：code:3000 message:request falied!
直接用 curl -S 该api提示错误
{"code":6100,"message":"\u8bf7\u6c42\u5931\u8d25\uff0c\u53c2\u6570\u9519\u8bef:[action]","codeDesc":"ActionNotFound"}
\u8bf7\u6c42\u5931\u8d25\uff0c\u53c2\u6570\u9519\u8bef 是 请求失败，参数错误

**Comment by zqfan** [comment]
lb尚未开发新版API，所以SDK中并不包含该产品。v2里的ReplaceCert接口还在，错误码3000表示是本地错误，php发送请求失败了

**Comment by zqfan** [comment]
负载均衡CLB现在应该已经支持了，这里先关闭issue。如果有问题请再打开。
