### ISSUE TITLE
本地调试出错

### ISSUE THREAD

**Issue by xulinyang** [TencentCloud/tencentcloud-sdk-php#21]
cURL error 60: SSL certificate problem: self signed certificate in certificate chain (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
请问怎么解决，可以不验证证书吗

**Comment by zqfan** [comment]
请提供下操作系统及版本、php版本、openssl版本信息，好帮助我们定位问题，谢谢

**Comment by 520aisu** [comment]
我也遇到了这个问题，我是win10系统，php5.5.38，开启了openssl扩展

**Comment by zqfan** [comment]
@520aisu 可以参考下这篇文章https://blog.csdn.net/The_classic3/article/details/79908934

**Comment by 520aisu** [comment]
他这个是用curl请求的吗，我怎么在sdk里面搜索不到 
找不到curl网址CURLOPT_URL函数

**Comment by 520aisu** [comment]
他这个是用curl请求的吗，我怎么在sdk里面搜索不到
找不到curl网址CURLOPT_URL函数  @zqfan

**Comment by zqfan** [comment]
使用的是GuzzleHttp，可以参考下说明：

> No system CA bundle could be found in any of the the common system locations.
> PHP versions earlier than 5.6 are not properly configured to use the system's
> CA bundle by default. In order to verify peer certificates, you will need to
> supply the path on disk to a certificate bundle to the 'verify' request
> option: http://docs.guzzlephp.org/en/latest/clients.html#verify. If you do not
> need a specific certificate bundle, then Mozilla provides a commonly used CA
> bundle which can be downloaded here (provided by the maintainer of cURL):
> https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt. Once
> you have a CA bundle available on disk, you can set the 'openssl.cafile' PHP
> ini setting to point to the path to the file, allowing you to omit the 'verify'
> request option. See http://curl.haxx.se/docs/sslcerts.html for more
> information.

总之就是得告诉php你的证书文件在哪儿，由于我无法复现这个问题，请你先试一试吧

**Comment by zqfan** [comment]
相关内容已更新到了首页readme
