### ISSUE TITLE
GuzzleHttp和laravel 还有yii自带的GuzzleHttp冲突啊，怎么解决

### ISSUE THREAD

**Issue by xshnjau** [TencentCloud/tencentcloud-sdk-php#22]

**Comment by zqfan** [comment]
laravel和yii的依赖文件中并没有guzzlehttp，你说的冲突具体指什么呢？
此sdk依赖的guzzlehttp是6.3.x版本

**Comment by chengyaozong** [comment]
是自动加载的TCloudAutoLoader方法开头的三个require_once写的有问题，估计是拿自己环境写的，不能通用，yii和laravel去掉开头require_once那三行就行了，不需要

**Comment by ly827** [comment]
> 是自动加载的TCloudAutoLoader方法开头的三个require_once写的有问题，估计是拿自己环境写的，不能通用，yii和laravel去掉开头require_once那三行就行了，不需要

对的 文档写的真垃圾

**Comment by zqfan** [comment]
现在已经移除了源码安装方式，必须使用composer安装
