### ISSUE TITLE
请支持分包，参考 alibabacloud/sdk

### ISSUE THREAD

**Issue by xiaohuilam** [TencentCloud/tencentcloud-sdk-php#32]

**Comment by zqfan** [comment]
请问分包的必要性是什么呢？
SDK开发者最开始有考虑过分包，以及优缺点，但后来放弃了，其中一条理由是AWS没有分包。

**Comment by liuyi** [comment]
就想用个短信通知而已，并不是所有人都用腾讯云全家桶呀

**Comment by yunwuxin** [comment]
@zqfan 分包吧  你这每天一个版本谁受得了

**Comment by yunwuxin** [comment]
现在这个包解压后 已经40M左右了   我就用了一个验证码的功能    你们还是版本帝    每次更新解压都贼慢

**Comment by zqfan** [comment]
阿里云把原先的分包项目https://github.com/aliyun/aliyun-openapi-php-sdk废弃了，
![image](https://user-images.githubusercontent.com/2180987/87123240-ee89ca00-c2b8-11ea-91fa-340c4e174431.png)
又搞了个新的https://github.com/aliyun/openapi-sdk-php ，我们这个恰好类似。

**Comment by zqfan** [comment]
我们考虑下吧，应该还是可以做的

**Comment by zqfan** [comment]
> @zqfan 分包吧 你这每天一个版本谁受得了

可以看changelog，你关心的包有更新，再更新sdk，生产环境一般还是钉死一个版本的

**Comment by yunwuxin** [comment]
> 阿里云把原先的分包项目[https://github.com/aliyun/aliyun-openapi-php-sdk废弃了，](https://github.com/aliyun/aliyun-openapi-php-sdk%E5%BA%9F%E5%BC%83%E4%BA%86%EF%BC%8C)
> ![image](https://user-images.githubusercontent.com/2180987/87123240-ee89ca00-c2b8-11ea-91fa-340c4e174431.png)
> 又搞了个新的https://github.com/aliyun/openapi-sdk-php ，我们这个恰好类似。

不类似哦，他们每个都是独立的composer包，可以单独安装的，只是放在了一个仓库里

**Comment by zqfan** [comment]
> 不类似哦，他们每个都是独立的composer包，可以单独安装的，只是放在了一个仓库里
哦，他们把composer.json塞进了src目录下的每个模块里了。。。

**Comment by yaowenqiang** [comment]
这个有计划什么时候分吗？

**Comment by xiaohuilam** [comment]
@zqfan

希望腾讯云提高这个需求的权重.
因为你们不分包每天浪费全国多少 CPU.

**Comment by zqfan** [comment]
可以使用composer require tencentcloud/cvm指定只安装cvm产品代码包，其他产品类似处理
