### ISSUE TITLE
DescribeLiveStreamPublishedListRequest()接口有问题啊

### ISSUE THREAD

**Issue by haibingxu** [TencentCloud/tencentcloud-sdk-php#37]
code:InvalidParameterValue message:StartTime must less than EndTime! requestId:b094d32f-
$params = '{"DomainName":"XXX","EndTime":"2019-09-22 01:01:01","StartTime":"2019-09-12 01:01:01"}';
写的时间没有问题吧，但总是提示
code:InvalidParameterValue message:StartTime must less than EndTime! requestId:b094d32f-

**Comment by zqfan** [comment]
看下接口的描述和字段的描述吧，我记得直播的接口查时间段似乎只能七天内，这个报错也许不够友好，你先试试缩短时间间隔吧。如果ok的话，那就是报错的信息有误，给云直播提工单反馈下
