### ISSUE TITLE
什么时候支持云直播、云点播

### ISSUE THREAD

**Issue by BEIBEI123** [TencentCloud/tencentcloud-sdk-php#4]
sdk3.0 什么时候支持云直播、云点播

**Comment by zqfan** [comment]
sdk 3.0是API 3.0的配套工具。
云直播和云点播暂无明确支持API3.0的日期，要看相关产品的决策和开发人员的进度而定，请耐心等待，并关注腾讯云官网。

**Comment by zqfan** [comment]
云直播和云点播现已开放部分API，SDK中已包含
