### ISSUE TITLE
严谨性问题啊哥们

### ISSUE THREAD

**Issue by yejiansnake** [TencentCloud/tencentcloud-sdk-php#41]
类 TencentCloud\Common\AbstractClient::doRequestWithTC3 
这个方法里面调用了 date_default_timezone_set('UTC'); 但是只设置啊，没有将原来的环境信息保存下来在使用完成后还原回去。

        $saveTimeZone = date_default_timezone_get();
        date_default_timezone_set('UTC');
        .........
        date_default_timezone_set($saveTimeZone);

起码加上这个把

**Comment by zqfan** [comment]
是的，以前是用的这种方式，后来接到其他用户报告，已经在https://github.com/TencentCloud/tencentcloud-sdk-php/commit/c6257e32088c323b403157eab5352832f5b6578d 中改用gmdate函数，将其修复了，您可以升级到3.0.67及以上版本，看是否能解决您的问题
