### ISSUE TITLE
在命令行下长时间运行(遍历)操作, cpu占用百分比会缓慢上升:SearchFaces和DetectFace接口

### ISSUE THREAD

**Issue by tsingyan** [TencentCloud/tencentcloud-sdk-php#45]

**Comment by tsingyan** [comment]
laravel console模式下

**Comment by zqfan** [comment]
@tsingyan 请问能麻烦提供更具体点的信息吗？例如您是一直使用Client不释放，还是每个请求都初始化一个Client？由于是首次遇到这种反馈，如果方便的话，可以把您代码中敏感信息（如密钥等）删除后，贴个大致的用法吗？

**Comment by tsingyan** [comment]
详细已发到gmail邮箱
