### ISSUE TITLE
The action not support this region

### ISSUE THREAD

**Issue by fisher7757** [TencentCloud/tencentcloud-sdk-php#46]
句法依存分析(DependencyParsing)，提示“此操作不支持此区域”,选了所有地区都不支持...
`<?php
require_once '../../../TCloudAutoLoader.php';
use TencentCloud\Common\Credential;
use TencentCloud\Common\Profile\ClientProfile;
use TencentCloud\Common\Profile\HttpProfile;
use TencentCloud\Common\Exception\TencentCloudSDKException;
use TencentCloud\Nlp\V20190408\NlpClient;
use TencentCloud\Nlp\V20190408\Models\DependencyParsingRequest;
try {

    $cred = new Credential("AK", "gTSh");//敏感词汇，删除了
    $httpProfile = new HttpProfile();
    $httpProfile->setEndpoint("nlp.ap-shanghai.tencentcloudapi.com");
      
    $clientProfile = new ClientProfile();
    $clientProfile->setHttpProfile($httpProfile);
    $client = new NlpClient($cred, "ap-shanghai", $clientProfile);

    $req = new DependencyParsingRequest();
    
    $params = '{"Text":"你好帅"}';
    $req->fromJsonString($params);

    $resp = $client->DependencyParsing($req);

    print_r($resp->toJsonString());
}
catch(TencentCloudSDKException $e) {
    echo $e;
}`

**Comment by fisher7757** [comment]
提示[TencentCloud\Common\Exception\TencentCloudSDKException] code:UnsupportedRegion message:The action not support this region. requestId:f2542b11-8b13-4910-9330-b6846464ce56

**Comment by fisher7757** [comment]
广州。希望新增上海地区

**Comment by zqfan** [comment]
业务部署只在部分区域，则只能指定那几个地域访问。可以到控制台工单系统提咨询类工单，问问nlp有没有计划支持上海地域
