### ISSUE TITLE
Proxy Setting？

### ISSUE THREAD

**Issue by diaolingzc** [TencentCloud/tencentcloud-sdk-php#47]
![image](https://user-images.githubusercontent.com/21998370/71229948-8b3b4900-2322-11ea-86d9-8ab48353cca2.png)

依赖了`guzzle`，为什么不把 `proxy` 暴露出来呢？ 修改系统环境变量，这是什么奇葩操作？

**Comment by kaisco** [comment]
使用系统环境变量来解决代理问题确实有些片面，赞成把guzzle的配置暴露出来。
