### ISSUE TITLE
注释写的有问题

### ISSUE THREAD

**Issue by yunwuxin** [TencentCloud/tencentcloud-sdk-php#49]
![image](https://user-images.githubusercontent.com/2168125/71461056-6c88f680-27e9-11ea-871b-cf3a224747f1.png)

这些注释写得真奇葩 你不写在类上  IDE怎么提示

**Comment by yunwuxin** [comment]
@zqfan @bobotoseeyou @AtlantisDe 
没人看下？

**Comment by zqfan** [comment]
@yunwuxin 看起来的确是生成时有问题，我们调整下

**Comment by yunwuxin** [comment]
@zqfan 还没解决么
