### ISSUE TITLE
这文档真的是狗屎

### ISSUE THREAD

**Issue by a1586256143** [TencentCloud/tencentcloud-sdk-php#50]
1.下载代码，按照源码方式运行，一直报错，找不到GuzzleHttp/functions.php文件，我以为要composer install，然而并没有什么用，最后发现注释掉TCloudAutoLoader.php的三行required_once就行了
2.想着，能运行就可以了，可以跑起来了，想想就兴奋，结果，打开examples下的文件一看，注释是很多，不得不承认，在这上面花了不少功夫，但是能不能有个注释，告诉我，这个demo是干嘛的？文件名起的叼的一皮，也要能看的懂啊！！！

**Comment by a1586256143** [comment]
最后，无力吐槽了，去阿里找替代的产品吧

**Comment by AtlantisDe** [comment]
哈哈哈...................!

**Comment by zqfan** [comment]
examples文件夹下的是部分产品提供的部分示例，大多是针对某个特定接口的演示，文件名通常就是接口名。
对于第一点，这个目前是为了照顾很多只会用源码的开发者，所以导出时vendor目录是不包含的，在github上点下载是无法得到这个目录下的源文件的，得使用git clone或者文档里提供的打包源码下载地址才可以。
对于第二点，你可以对比下阿里的示例文档是怎么写的
![image](https://user-images.githubusercontent.com/2180987/78471314-eaeb2200-7762-11ea-9353-94c729727a23.png)
