### ISSUE TITLE
文件引用出错

### ISSUE THREAD

**Issue by yy87945120** [TencentCloud/tencentcloud-sdk-php#54]
composer下载的vender的文件目录跟api exloper引用的文件里的引入文件路径

**Comment by ColgateShu** [comment]
![image](https://user-images.githubusercontent.com/15250471/73119483-932f7e00-3f9d-11ea-9dee-f6df7221607f.png)
希望可以帮到你，这是我的代码示例

**Comment by zqfan** [comment]
examples里面和API Explorer里面使用的都是相对路径，跟你实际文件的位置相关
