### ISSUE TITLE
namespace 大小写问题

### ISSUE THREAD

**Issue by Frank-Dell** [TencentCloud/tencentcloud-sdk-php#57]
/src/TencentCloud/Sms/V20190711/SmsClient.php 第 18 行：
`namespace TencentCloud\Sms\V20190711;`
/examples/sms/v20190711/SendSms.php 第 4 行：
`use TencentCloud\Sms\v20190711\SmsClient;`
一个写成了 “V20190711”，另一个写成了 “v20190711”。

直接使用将导致运行时错误。

将
`use TencentCloud\Sms\v20190711\SmsClient;`
修改为
`use TencentCloud\Sms\V20190711\SmsClient;`
可解决此问题。

**Comment by zqfan** [comment]
感谢反馈这个问题，已由此次提交修复：https://github.com/TencentCloud/tencentcloud-sdk-php/commit/929886902ae5df49a8272b35a506776ebafaec9d

**Comment by Frank-Dell** [comment]
> 感谢反馈这个问题，已由此次提交修复：[9298869](https://github.com/TencentCloud/tencentcloud-sdk-php/commit/929886902ae5df49a8272b35a506776ebafaec9d)

谢谢
