### ISSUE TITLE
分块上传音频或视频的接口在哪？哪位大佬可以告知一下

### ISSUE THREAD

**Issue by yzq170320** [TencentCloud/tencentcloud-sdk-php#58]

**Comment by zqfan** [comment]
请问是哪个产品的？
如果是云点播的，可以参考这里：https://cloud.tencent.com/document/product/266/9759

**Comment by yzq170320** [comment]
@zqfan 简单对象存储，使用复合的上传方法，80M文件就会出现504 gateway time-out .具体方法参考
![image](https://user-images.githubusercontent.com/26958549/77514194-5571a780-6eb1-11ea-871f-fa0bb811c483.png)

**Comment by yzq170320** [comment]
try {
    $result = $cosClient->Upload(
        $bucket = 'examplebucket-1250000000', //格式：BucketName-APPID
        $key = 'exampleobject',
        $body = fopen('path/to/localFile', 'rb')
    );
    // 请求成功
    print_r($result);
} catch (\Exception $e) {
    // 请求失败
    echo($e);
}

**Comment by zqfan** [comment]
@yzq170320 需要咨询下对象存储cos。
如果不是cos的问题，可以看看你本地是否有代理之类的，可能时间过长，被你的代理网关断开了

**Comment by yzq170320** [comment]
nginx代理，超过2分钟没有响应就超时的。这种情况应该怎么处理，对象存储的分块上传机制是怎么样的？不是没上传一块给一个回馈吗？

**Comment by zqfan** [comment]
抱歉，不太清楚对象存储接口的机制，还是提工单咨询下对象存储的相关人员吧
