### ISSUE TITLE
为什么sdk 下载不下来，clone也不行，composer也不行

### ISSUE THREAD

**Issue by hexin001** [TencentCloud/tencentcloud-sdk-php#59]
为什么sdk 下载不下来，clone也不行，composer也不行

**Comment by zqfan** [comment]
具体什么问题？不行指的是什么，贴一下截图看看

**Comment by zqfan** [comment]
![image](https://user-images.githubusercontent.com/2180987/78471040-a78fb400-7760-11ea-874f-6b25b90c7fba.png)
