### ISSUE TITLE
如果只要腾讯云里面的部分功能，怎么筛选出我需要的src里面的文件呢？

### ISSUE THREAD

**Issue by cryschao** [TencentCloud/tencentcloud-sdk-php#62]
实际案例是，我只用到了验证码的功能，但是sdk包没有好的办法可以筛选出验证码功能的需求文件。
请问有什么好的办法吗。

**Comment by zqfan** [comment]
目前是所有产品都打包在一起的。是有什么大小方面的限制要考虑裁剪吗？
在src/TencentCloud/下面Common目录是必须的，其他各目录分别对应一个产品，假设只要ocr的，就只留Ocr和Common目录。不过这样裁剪后下次如果更新还是会有全部产品的。

**Comment by buildyuan** [comment]
"require": {
    "tencentcloud/captcha": "^3.0"
  },
