### ISSUE TITLE
很多文件，但是不知道怎么用

### ISSUE THREAD

**Issue by MiracleDragon** [TencentCloud/tencentcloud-sdk-php#63]
比如我要用某个功能，我应该怎么用，我从哪里找这个文件引入，比如我要用 https://cloud.tencent.com/document/product/647/40496 房间管理相关接口 > 移出用户，那我该怎样用？我怎么知道我去哪里找对应的文件引入呢

**Comment by zqfan** [comment]
建议使用这篇文档中提到的API Explorer工具，https://console.cloud.tencent.com/api/explorer?Product=trtc&Version=2019-07-22&Action=RemoveUser
可以直接生成SDK代码运行
![image](https://user-images.githubusercontent.com/2180987/84224559-6b395500-ab0f-11ea-9408-ef293271da86.png)
