### ISSUE TITLE
Class 'TencentCloud\Common\Credential' not found

### ISSUE THREAD

**Issue by fengxiaolei** [TencentCloud/tencentcloud-sdk-php#65]
明明引入了，一直报这个错，Demo一直跑不起来。请问下是什么问题？

**Comment by zqfan** [comment]
麻烦贴一下完整的报错信息，所使用的php版本

**Comment by zqfan** [comment]
没有这些信息难以定位，盲猜可能是引用的路径不对。
例如你的代码中是 requre "vendor/autoload.php"，但是执行的时候不在项目的根目录下，或者你的文件和vendor不是平级的。建议在项目根目录下执行，如果不能的话，引用的时候用绝对路径而不是相对路径，例如你的代码在和vendor平级的src目录下，那么引用的时候用requre __DIR__."/../vendor/autoload.php"
