### ISSUE TITLE
Bad stream status

### ISSUE THREAD

**Issue by fanyoujian** [TencentCloud/tencentcloud-sdk-php#67]
$req = new CreateLiveRecordRequest();
            $req->setAppName($this->appName);
            $req->setDomainName($this->domainName);
            $req->setStreamName($streamName);
            $req->setHighlight(1);
            $resp = $client->CreateLiveRecord($req);
报错： Bad stream status

**Comment by zqfan** [comment]
麻烦贴一下完整报错和堆栈。
如果有request id，这个Bad stream status报错可能是接口后端返回的，可以到控制台提工单给云直播业务咨询下。

> ```
> $req = new CreateLiveRecordRequest();
>         $req->setAppName($this->appName);
>         $req->setDomainName($this->domainName);
>         $req->setStreamName($streamName);
>         $req->setHighlight(1);
>         $resp = $client->CreateLiveRecord($req);
> ```
> 
> 报错： Bad stream status

**Comment by zqfan** [comment]
由于太久没给出信息，这里先关闭。如有更新可重新打开
