### ISSUE TITLE
DescribeTaskDetailRequest 请求 返回数据 fileUrl 为空

### ISSUE THREAD

**Issue by fanyoujian** [TencentCloud/tencentcloud-sdk-php#68]
{"TaskType":"EditMedia","Status":"FINISH","CreateTime":"2020-06-09T09:17:55Z","BeginProcessTime":"2020-06-09T09:17:55Z","FinishTime":"2020-06-09T09:17:56Z","EditMediaTask":{"TaskId":"1257290329-EditMedia-4f1921b9fbcb8149e9719978212b5636t0","Status":"FINISH","ErrCode":40000,"Message":"invalid
input","Input":{"InputType":"File","FileInfoSet":[{"FileId":"5285890803951322434","StartTimeOffset":0,"EndTimeOffset":0},{"FileId":"5285890803951423423","StartTimeOffset":0,"EndTimeOffset":0},{"FileId":"5285890803953524953","StartTimeOffset":0,"EndTimeOffset":0},{"FileId":"5285890803953666320","StartTimeOffset":0,"EndTimeOffset":0}],"StreamInfoSet":[]},"Output":{"FileType":"","FileUrl":"","FileId":"","MediaName":"","ClassId":0,"ExpireTime":"0000-00-00T00:00:00Z"},"ProcedureTaskId":"","SessionContext":"","SessionId":""},"RequestId":"633c1d78-bb1d-47ea-aa7a-8acb5a336795"}

**Comment by zqfan** [comment]
你的输入有问题，处理失败了，注意看sdk中对返回字段ErrCode和Message的注释（或者到官网看接口文档）

**Comment by fanyoujian** [comment]
参数不合法，不应该请求成功啊Array
(
[TaskId] => 1257290329-EditMedia-452d01df6c249ecfb48c71f15198b0e7t0
[RequestId] => 61cd3a2b-6859-4f14-b9e3-9d0027864e61

**Comment by fanyoujian** [comment]
### [`#[](url)`](url)
![image](https://user-images.githubusercontent.com/10875463/84225207-20204180-ab11-11ea-8be7-a86a38124f8d.png)
![image](https://user-images.githubusercontent.com/10875463/84225242-3928f280-ab11-11ea-85b1-8569b0d576d0.png)


参数哪里错了

**Comment by zqfan** [comment]
vod云直播的回复：“业务场景是离线任务。按照我们的设计，有一部分参数错误是在 API 调用时，同步返回参数错误的。另一部分，是要在任务发起之后，检查到的错误，需要在回调信息中给出。”
我个人认为这种设计也是合理的，你看看是否能解答你的疑惑？
