### ISSUE TITLE
composer 下载的文件。。example 里很多都没有。

### ISSUE THREAD

**Issue by richerdyoung** [TencentCloud/tencentcloud-sdk-php#69]
翻看了 github 所有的 issue。才看到。你们的 请求示例。需要登录 进去，才可以看到各个接口的请求示例，  建议 你们直接 把 这个事情，写在 readme 里。。免得 被开发者骂

各语言请求示例： （需要登录）
https://console.cloud.tencent.com/api/explorer?Product=live&Version=2018-08-01&Action=DescribeLiveStreamOnlineList&SignVersion=

**Comment by zqfan** [comment]
感谢建议，我们更新下文档
