### ISSUE TITLE
日志服务API未实现？

### ISSUE THREAD

**Issue by xiaohuilam** [TencentCloud/tencentcloud-sdk-php#7]
[文档](https://cloud.tencent.com/document/product/614/16907)

**Comment by zqfan** [comment]
这个sdk是配套API 3.0的，日志服务并未支持API 3.0。
如有需要，可以在腾讯云控制台工单系统中提单给 日志服务  这个产品，让他们支持API 3.0。

**Comment by zqfan** [comment]
日志服务已决定不接入云api3.0，此SDK不会包含日志服务了。请知悉。
