### ISSUE TITLE
vod 缺少一些文件

### ISSUE THREAD

**Issue by luckyue-liang** [TencentCloud/tencentcloud-sdk-php#72]
https://console.cloud.tencent.com/api/explorer?Product=vod&Version=2018-07-17&Action=CreateProcedureTemplate&SignVersion=

如：
看调试工具是有这个类  TencentCloud\Vod\V20180717\Models\CreateProcedureTemplateRequest ；但实际在 SDK 包里并没有。

**Comment by zqfan** [comment]
需要升级到最新版本，新发布的 接口在旧版本的sdk中是没有的
