### ISSUE TITLE
不分包有太多坑

### ISSUE THREAD

**Issue by shh12580** [TencentCloud/tencentcloud-sdk-php#75]
坑1：发布线上环境时，Vendor有上万个文件，其中9781个文件是Tencentcloud的，导致发布的包特别大，占了50MB+
坑2：composer文件下的autoload_classmap.php有2.5MB的代码，autoload_static.php有2.6MB的代码，95%的行都是Tencentcloud的，一个代码文件有上万行代码，加载效率不敢想象，浪费了太多的内存消耗
先不管阿里分包和不分包（他们有分包版本和不分包版本），也先不说分包和不分包的优缺点，单看这俩坑就觉得目前这种使用一个组件，结果要拉个全家桶的方式就特别的不合理

**Comment by zqfan** [comment]
可以使用composer require tencentcloud/cvm指定只安装cvm产品代码包
