### ISSUE TITLE
请支持GuzzleHttp ^7.0

### ISSUE THREAD

**Issue by Celaraze** [TencentCloud/tencentcloud-sdk-php#80]
感谢

**Comment by caizhigang97** [comment]
`tencentcloud-sdk-php`最新的版本不兼容Laravel8.
![image](https://user-images.githubusercontent.com/21142662/92548804-850f4300-f28a-11ea-926d-9d30920c781e.png)

- Laravel的建议
![image](https://user-images.githubusercontent.com/21142662/92548821-91939b80-f28a-11ea-908b-0ebc2a722b2c.png)

- `tencentcloud-sdk-php`的要求
![image](https://user-images.githubusercontent.com/21142662/92548850-9f492100-f28a-11ea-9377-d9b7bba6bc55.png)

暂时先把`composer.json` 中的`guzzlehttp/guzzle`降级到了`^6.3` 解决这个冲突的问题.
希望工程师能尽快修复这个问题.

**Comment by haxifang-aircos** [comment]
刚哥，没想到在这里遇见你了~我也在照这个问题解决方案
