### ISSUE TITLE
composer 无法下载

### ISSUE THREAD

**Issue by anyluckwell** [TencentCloud/tencentcloud-sdk-php#83]

**Comment by zqfan** [comment]
请贴一下具体的报错信息。
另外，建议使用国内镜像源，文档中有提及。直接使用海外官方站点可能因为网速原因或者其他原因导致失败。

**Comment by zqfan** [comment]
由于长时间没有反馈，关闭此单。
![image](https://user-images.githubusercontent.com/2180987/130577657-c11c4c70-0e7f-49d0-adc8-8233b34555e7.png)
