### ISSUE TITLE
PHP 5.4.44  能不能用，如果不想升级有没有解决方案？

### ISSUE THREAD

**Issue by gezsops** [TencentCloud/tencentcloud-sdk-php#84]
PHP 5.4.44  能不能用，如果不想升级有没有解决方案？

**Comment by zqfan** [comment]
https://github.com/TencentCloud/tencentcloud-sdk-php/blob/master/src/TencentCloud/Common/AbstractClient.php#L45
将这里的版本限制降低，执行下代码，看报什么错误。

我们并未对低于要求的版本进行测试，别说兼容性了，甚至是跑不起来的。php官方也不再维护这么老的版本了，你不可能永远都停留在5.4，对吧。

**Comment by zqfan** [comment]
因长期没有反馈，关闭此单
