### ISSUE TITLE
新增加的guzzle7.0+版本引起了兼容性问题

### ISSUE THREAD

**Issue by xiaohuanlin** [TencentCloud/tencentcloud-sdk-php#86]
php版本：7.0
引起报错
Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in D:\xxx\src\vendor\guzzlehttp\guzzle\src\Client.php on line 203
![image](https://user-images.githubusercontent.com/33860497/105684506-01e84400-5f30-11eb-81fe-853b0d90d9f4.png)

**Comment by zqfan** [comment]
composer.json里指定的是或关系，如果高版本不满足要求，就使用6.x版本。你的php7.0能安装7.x的guzzlehttp，可能是其他库引起的
