### ISSUE TITLE
TypeError,Dimension.php:57

### ISSUE THREAD

**Issue by MarkGor** [TencentCloud/tencentcloud-sdk-php#91]
监控，CVM部分；
使用API EXPLORER的代码，

传入参数：
`
Array
(
    [Namespace] => CVM
    [MetricName]=> BaseCpuUsage
    [Instances] => Array
        (
            [0] => Array
                (
                    [Dimensions] => Array
                        (
                            [Name] => InstanceId
                            [Value] => ins-xx
                        )

                )

            [1] => Array
                (
                    [Dimensions] => Array
                        (
                            [Name] => InstanceId
                            [Value] => ins-xxx
                        )

                )

            [2] => Array
                (
                    [Dimensions] => Array
                        (
                            [Name] => InstanceId
                            [Value] => ins-xxxx
                        )

                )

        )

)
`
出错在Instances节点，
数据结构为Dimensions=>[Name,Value]
但Dimensions中的deserial直接忽略Dimensions,判断Name和Value。

`
TypeError: array_key_exists(): Argument #2 ($array) must be of type array, string given in /api/logger/vendor/tencentcloud/tencentcloud-sdk-php/src/TencentCloud/Monitor/V20180724/Models/Dimension.php:57

Stack trace:

#0 /api/logger/vendor/tencentcloud/tencentcloud-sdk-php/src/TencentCloud/Monitor/V20180724/Models/Dimension.php(57): array_key_exists()

#1 /api/logger/vendor/tencentcloud/tencentcloud-sdk-php/src/TencentCloud/Monitor/V20180724/Models/Instance.php(53): TencentCloud\Monitor\V20180724\Models\Dimension->deserialize()

#2 /api/logger/vendor/tencentcloud/tencentcloud-sdk-php/src/TencentCloud/Monitor/V20180724/Models/GetMonitorDataRequest.php(101): TencentCloud\Monitor\V20180724\Models\Instance->deserialize()

#3 /api/logger/vendor/tencentcloud/tencentcloud-sdk-php/src/TencentCloud/Common/AbstractModel.php(105): TencentCloud\Monitor\V20180724\Models\GetMonitorDataRequest->deserialize()

#4 /api/logger/app/lib/qcloud/helpers/cvm.php(78): TencentCloud\Common\AbstractModel->fromJsonString()

#5 /api/logger/app/controller/Qcloud.php(16): app\lib\qcloud\helpers\cvm->getResult()
`

**Comment by zqfan** [comment]
麻烦把api explorer链接贴一下，sdk中的代码是正确的，要查一下是否是api explorer生成代码错了

**Comment by MarkGor** [comment]
> 麻烦把api explorer链接贴一下，sdk中的代码是正确的，要查一下是否是api explorer生成代码错了

这个是我看错了，
Dimensions节点下是array(array(....))

api explorer没错
sdk中也没错
