### ISSUE TITLE
文件系统监控 读写次数类 异常

### ISSUE THREAD

**Issue by MarkGor** [TencentCloud/tencentcloud-sdk-php#92]
Namespace=QCE/CFS
MetricName=DataReadIOPS|DataWriteIOPS
均返回 "namespace or metricName invalid"
其余的指标都能正常返回

**Comment by zqfan** [comment]
如果是这个接口，https://cloud.tencent.com/document/product/248/31014
如文档中所述，metricname只支持单指标，MetricName=DataReadIOPS|DataWriteIOPS ，这种写法应该是不行的
不过我也不是做监控的，建议到控制台提工单到云监控产品咨询下

**Comment by MarkGor** [comment]
> 如果是这个接口，https://cloud.tencent.com/document/product/248/31014
> 如文档中所述，metricname只支持单指标，MetricName=DataReadIOPS|DataWriteIOPS ，这种写法应该是不行的
> 不过我也不是做监控的，建议到控制台提工单到云监控产品咨询下

我只是举例，
我是单个指标传入的，
只要是传入DataReadIOPS 或 传入DataWriteIOPS
都会出错，其余的都正常

**Comment by zqfan** [comment]
那就只能提工单了，因为SDK只是把请求发到服务端，服务端如果自己逻辑出了问题，sdk是解决不了的。
