### ISSUE TITLE
composer 下载报错 

### ISSUE THREAD

**Issue by gitxinyi** [TencentCloud/tencentcloud-sdk-php#96]
![image](https://user-images.githubusercontent.com/28300658/130405300-6feae8ba-139a-43c2-a770-7f811e741e18.png)
composer 源已切换至腾讯

**Comment by gitxinyi** [comment]
看了一下历史提交问题，sdk下载一直有问题，去年就有人反馈了，还没解决，这样的产品谁敢用？

**Comment by zqfan** [comment]
目前，此sdk并未依赖或间接依赖monolog和googleads相关模块。请自行检查下你的项目依赖问题。
![image](https://user-images.githubusercontent.com/2180987/130581816-a980dda2-a1c6-48b8-9696-52cb36d0a7ad.png)
sdk一直可以正常从composer官方或腾讯镜像源下载，目前为止没有发现由于sdk自身问题导致用户无法下载的情况。
